# Example: Build Debug APK
# Copy to .github/workflows/ to use
# No secrets required - builds debug APK only

name: Build APK

on:
  push:
    branches: [main]
    paths:
      - 'korge-game/**'
      - 'shared/**'
      - '.github/workflows/build-apk.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: |
          chmod +x ./gradlew
          chmod +x ./korge-game/gradlew

      - name: Build shared module (JVM only)
        run: ./gradlew :shared:jvmJar

      - name: Build Debug APK
        working-directory: korge-game
        run: ./gradlew assembleDebug

      - name: Get version info
        id: version
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: |
          # Try different possible APK names
          mv korge-game/build/outputs/apk/debug/*-debug.apk \
             korge-game/build/outputs/apk/debug/App-${{ steps.version.outputs.date }}-${{ steps.version.outputs.sha_short }}.apk || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-${{ steps.version.outputs.date }}
          path: korge-game/build/outputs/apk/debug/*.apk
          retention-days: 30
          if-no-files-found: error
