name: RuStore - Build & Upload Draft

on:
  push:
    tags:
      - 'v*'  # Триггер на теги вида v1.0.0
  workflow_dispatch:

env:
  PACKAGE_NAME: com.idledungeonheroes.game

jobs:
  # ========================================
  # Job 1: Build Release APK
  # ========================================
  build-release:
    name: Build Release APK
    runs-on: ubuntu-latest

    outputs:
      version_code: ${{ steps.version.outputs.version_code }}
      version_name: ${{ steps.version.outputs.version_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Grant execute permission
        run: |
          chmod +x ./gradlew
          chmod +x ./korge-game/gradlew

      - name: Get version info
        id: version
        run: |
          VERSION_CODE=$(git rev-list --count HEAD)
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT

          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_NAME="${GITHUB_REF#refs/tags/v}"
          else
            VERSION_NAME="$(git describe --tags --always)"
          fi
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

          echo "Version Code: $VERSION_CODE"
          echo "Version Name: $VERSION_NAME"

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > korge-game/release.keystore

      - name: Build shared module (JVM only)
        run: ./gradlew :shared:jvmJar

      - name: Build Release APK
        working-directory: korge-game
        env:
          VERSION_CODE: ${{ steps.version.outputs.version_code }}
          VERSION_NAME: ${{ steps.version.outputs.version_name }}
        run: |
          # KorGE ignores signing parameters, so we build unsigned first
          ./gradlew assembleRelease \
            -x generateReleaseLintVitalReportModel \
            -x lintVitalAnalyzeRelease \
            -x lintVitalRelease \
            -Pandroid.injected.version.code="$VERSION_CODE" \
            -Pandroid.injected.version.name="$VERSION_NAME"

      - name: Sign APK with release keystore
        working-directory: korge-game
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          # Find APK signer
          APKSIGNER=$(find $ANDROID_HOME/build-tools -name "apksigner" | sort -V | tail -1)
          echo "Using apksigner: $APKSIGNER"

          # Sign APK with our release keystore
          $APKSIGNER sign \
            --ks release.keystore \
            --ks-key-alias "$KEY_ALIAS" \
            --ks-pass pass:"$KEYSTORE_PASSWORD" \
            --key-pass pass:"$KEY_PASSWORD" \
            --out build/outputs/apk/release/IdleDungeonHeroes-${{ steps.version.outputs.version_name }}.apk \
            build/outputs/apk/release/IdleDungeonHeroes-release.apk

          # Verify signature
          $APKSIGNER verify --print-certs build/outputs/apk/release/IdleDungeonHeroes-${{ steps.version.outputs.version_name }}.apk

          # Remove unsigned APK
          rm -f build/outputs/apk/release/IdleDungeonHeroes-release.apk

      - name: Cleanup Keystore
        if: always()
        run: rm -f korge-game/release.keystore

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-${{ steps.version.outputs.version_name }}
          path: korge-game/build/outputs/apk/release/*.apk
          retention-days: 90
          if-no-files-found: error

  # ========================================
  # Job 2: Upload Draft to RuStore (automatic)
  # ========================================
  upload-draft-to-rustore:
    name: Upload Draft to RuStore
    needs: build-release
    runs-on: ubuntu-latest
    outputs:
      version_id: ${{ steps.draft.outputs.version_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk-${{ needs.build-release.outputs.version_name }}
          path: ./artifacts

      - name: List artifacts
        run: ls -la ./artifacts/

      - name: Setup Python for signing
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install cryptography requests

      - name: Get RuStore Auth Token
        id: auth
        env:
          RUSTORE_KEY_ID: ${{ secrets.RUSTORE_COMPANY_ID }}
          RUSTORE_PRIVATE_KEY: ${{ secrets.RUSTORE_CLIENT_SECRET }}
        run: |
          python3 << 'PYTHON_SCRIPT'
          import requests
          import os
          import base64
          from datetime import datetime, timezone
          from cryptography.hazmat.primitives import hashes, serialization
          from cryptography.hazmat.primitives.asymmetric import padding
          from cryptography.hazmat.backends import default_backend

          key_id = os.environ['RUSTORE_KEY_ID']
          private_key_pem = os.environ['RUSTORE_PRIVATE_KEY']

          # Convert to PEM format if needed
          if not private_key_pem.startswith('-----BEGIN'):
              private_key_pem = f"-----BEGIN PRIVATE KEY-----\n{private_key_pem}\n-----END PRIVATE KEY-----"

          # Load private key
          try:
              private_key = serialization.load_pem_private_key(
                  private_key_pem.encode(),
                  password=None,
                  backend=default_backend()
              )
          except Exception as e:
              print(f"Failed to load private key: {e}")
              exit(1)

          # Create ISO 8601 timestamp with milliseconds and timezone
          # Format: 2024-06-18T11:49:08.290+03:00
          now = datetime.now(timezone.utc)
          # Use 3 digits for milliseconds (not 6 for microseconds)
          timestamp = now.strftime('%Y-%m-%dT%H:%M:%S.') + f'{now.microsecond // 1000:03d}' + '+00:00'

          # Sign keyId + timestamp (concatenated) with SHA512withRSA
          data_to_sign = key_id + timestamp
          try:
              signature_bytes = private_key.sign(
                  data_to_sign.encode('utf-8'),
                  padding.PKCS1v15(),
                  hashes.SHA512()
              )
              signature = base64.b64encode(signature_bytes).decode('utf-8')
          except Exception as e:
              print(f"Signing error: {e}")
              exit(1)

          # Auth request - use keyId, not companyId!
          auth_data = {
              'keyId': key_id,
              'timestamp': timestamp,
              'signature': signature
          }

          print(f"Auth request: keyId={key_id}, timestamp={timestamp}")
          print(f"Data to sign: {data_to_sign}")
          print(f"Signature length: {len(signature)}")

          response = requests.post(
              'https://public-api.rustore.ru/public/auth',
              json=auth_data
          )

          print(f"Auth response: {response.text}")

          if response.status_code == 200:
              data = response.json()
              if data.get('code') == 'OK' and data.get('body', {}).get('jwe'):
                  token = data['body']['jwe']
                  with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                      f.write(f"token={token}\n")
                  print("Auth successful!")
              else:
                  print(f"Auth failed: {data}")
                  exit(1)
          else:
              print(f"Auth request failed: {response.status_code}")
              exit(1)
          PYTHON_SCRIPT

      - name: Create Draft Version
        id: draft
        env:
          AUTH_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          echo "Step 1: Creating draft version..."

          # Create draft version (JSON, no file)
          RESPONSE=$(curl -s -X POST "https://public-api.rustore.ru/public/v1/application/${{ env.PACKAGE_NAME }}/version" \
            -H "Public-Token: $AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"appType": "MAIN", "publishType": "MANUAL"}')

          echo "Create draft response: $RESPONSE"
          VERSION_ID=$(echo $RESPONSE | jq -r '.body.versionId // empty')

          if [ -z "$VERSION_ID" ] || [ "$VERSION_ID" = "null" ]; then
            echo "Failed to create draft version"
            echo "Response: $RESPONSE"
            echo "version_id=" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "✅ Created draft version: $VERSION_ID"
          echo "version_id=$VERSION_ID" >> $GITHUB_OUTPUT

      - name: Upload APK to Draft
        id: upload
        if: steps.draft.outputs.version_id != ''
        env:
          AUTH_TOKEN: ${{ steps.auth.outputs.token }}
          VERSION_ID: ${{ steps.draft.outputs.version_id }}
        run: |
          APK_FILE=$(ls ./artifacts/*.apk | head -1)
          APK_SIZE=$(stat -f%z "$APK_FILE" 2>/dev/null || stat -c%s "$APK_FILE")
          echo "Step 2: Uploading APK..."
          echo "File: $APK_FILE"
          echo "Size: $((APK_SIZE / 1024 / 1024)) MB"

          # Upload APK to the draft version
          RESPONSE=$(curl -s -X POST "https://public-api.rustore.ru/public/v1/application/${{ env.PACKAGE_NAME }}/version/$VERSION_ID/apk?servicesType=Unknown&isMainApk=true" \
            -H "Public-Token: $AUTH_TOKEN" \
            -F "file=@$APK_FILE")

          echo "Upload response: $RESPONSE"
          CODE=$(echo $RESPONSE | jq -r '.code // empty')

          if [ "$CODE" = "OK" ]; then
            echo "✅ APK uploaded successfully!"
            echo "upload_success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to upload APK"
            echo "Response: $RESPONSE"
            echo "upload_success=false" >> $GITHUB_OUTPUT
          fi

      - name: Draft Status
        run: |
          if [ -n "${{ steps.draft.outputs.version_id }}" ]; then
            echo "========================================="
            echo "✅ Draft uploaded to RuStore!"
            echo "========================================="
            echo "Package: ${{ env.PACKAGE_NAME }}"
            echo "Version: ${{ needs.build-release.outputs.version_name }}"
            echo "Version ID: ${{ steps.draft.outputs.version_id }}"
            echo ""
            echo "To submit for review, run workflow manually with action=submit_review"
            echo "========================================="
          else
            echo "========================================="
            echo "⚠️ Draft upload failed or skipped"
            echo "========================================="
            echo "Please upload APK manually to RuStore Console"
            echo "APK is available in GitHub Actions artifacts"
            echo "========================================="
          fi

  # ========================================
  # Job 3: Create GitHub Release
  # ========================================
  create-github-release:
    name: Create GitHub Release
    needs: [build-release, upload-draft-to-rustore]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk-${{ needs.build-release.outputs.version_name }}
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ needs.build-release.outputs.version_name }}
          body: |
            ## Idle Dungeon Heroes v${{ needs.build-release.outputs.version_name }}

            ### Downloads
            - **APK**: Direct install on Android devices

            ### RuStore
            Черновик загружен в RuStore. Для отправки на модерацию запустите workflow вручную с action=submit_review

            Version Code: `${{ needs.build-release.outputs.version_code }}`
          files: ./artifacts/*.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
